
services:
  auth_service:
    environment:
      - DJANGO_DEBUG=False               # в продакшене всегда выключен
    mem_limit: 1024m
    cpus: 1.0

  marketplace_service:
    environment:
      - DJANGO_DEBUG=False
    mem_limit: 1536m
    cpus: 1.2

  payment_service:
    environment:
      - DJANGO_DEBUG=False
    mem_limit: 1024m
    cpus: 1.0

  postgres:
    # в продакшене обычно оставляем те же переменные, но можно добавить:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # если нужен постоянный бэкап, подключаем отдельный volume, например:
    # - pgdata_prod:/var/lib/postgresql/data

  redis:
    # никаких особых изменений
    # (можно добавить persist‑volume, если нужен кеш между рестартами)
    # volumes:
    #   - redis_data:/data