name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: [5432:5432]
        options: >-
          --health-cmd "pg_isready -U dev"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports: [6379:6379]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (auth_service)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r services/auth_service/requirements.txt
          pip install pytest pytest-django

      - name: Install dependencies (marketplace_service)
        run: |
          source venv/bin/activate
          pip install -r services/marketplace_service/requirements.txt

      - name: Run tests (auth_service)
        env:
          DJANGO_SETTINGS_MODULE: auth_service.settings
          POSTGRES_DB: marketplace
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_HOST: localhost
        run: |
          source venv/bin/activate
          pytest services/auth_service/tests

      - name: Run tests (marketplace_service)
        env:
          DJANGO_SETTINGS_MODULE: marketplace.settings
          POSTGRES_DB: marketplace
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_HOST: localhost
        run: |
          source venv/bin/activate
          pytest services/marketplace_service/tests